export const imgs = {
  user_empty: require('../assets/imgs/img_empty.png'),
  icon_bell: require('../assets/imgs/icon_bell.png'),
  icon_search: require('../assets/icons/search.png'),
  plus: require('../assets/icons/plus.png'),
  trash: require('../assets/icons/trash.png'),
  arrow: require('../assets/icons/arrow.png'),
  calender: require('../assets/icons/calender.png'),
  clock: require('../assets/icons/clock.png'),
  bell: require('../assets/icons/bell.png'),
  logo: require('../assets/icons/logo.png'),
  close: require('../assets/icons/close.png'),
  arrowbottom: require('../assets/icons/arrowbottom.png'),
  delete: require('../assets/icons/deleteicon.png'),
  check: require('../assets/icons/check.png'),
};
